version: '3'

volumes:
  pg_data_store:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_store:/var/lib/postgresql/data
  backend:
    image: paleo8/online_store_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  gateway:
    image: paleo8/online_store_gateway
    volumes:
      - static:/static
      - media:/media
    depends_on:
    - backend
    ports:
      - 8000:80