# Generated by Django 3.2.16 on 2023-09-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
