# Generated by Django 3.2.16 on 2023-04-30 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='Адрес',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='Город',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='Имя',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='Индекс',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='Фамилия',
        ),
    ]
