# Generated by Django 3.2.16 on 2023-09-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Адрес',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Город',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Имя',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Индекс',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Фамилия',
        ),
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.CharField(default='Дж. Файзи 10', max_length=250, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Казань', max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='Фамилия', max_length=50, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Имя', max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=420000, max_length=20, verbose_name='Индекс'),
            preserve_default=False,
        ),
    ]
